name = "remix-cloudflare-workers"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

[site]
  bucket = "./public"

[build]
  command = "yarn run build"

[wasm_modules]
YOGA_WASM = "node_modules/yoga-wasm-web/dist/yoga.wasm"
RESVG_WASM = "node_modules/@resvg/resvg-wasm/index_bg.wasm"
