name = "remix-workers-satori"
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-10-11"
compatibility_flags= ["streams_enable_constructors"]

[site]
  bucket = "./public"

[build]
  command = "yarn run build"
  watch_dir = "app"

[wasm_modules]
YOGA_WASM = "node_modules/yoga-wasm-web/dist/yoga.wasm"
RESVG_WASM = "node_modules/@resvg/resvg-wasm/index_bg.wasm"
